# Write your MySQL query statement below
WITH TP AS(
    SELECT *,
        COUNT(LAT) OVER(PARTITION BY LAT,LON) AS COUNTLOC,
        COUNT(TIV_2015) OVER(PARTITION BY TIV_2015) AS COUNTTIV
    FROM INSURANCE 
)

SELECT ROUND(SUM(TIV_2016),2) AS TIV_2016
FROM TP
WHERE COUNTLOC=1 AND COUNTTIV>1
    