# Write your MySQL query statement below
WITH ALL_IDS AS(
    SELECT REQUESTER_ID AS ID
    FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID AS ID
    FROM REQUESTACCEPTED
)

SELECT ID, NUM
FROM(
    SELECT 
        ID, 
        COUNT(ID) AS NUM,
        RANK() OVER(ORDER BY COUNT(ID) DESC) AS RNK
    FROM ALL_IDS
    GROUP BY ID
) AS IDS
WHERE RNK=1

