# Write your MySQL query statement below
SELECT
    VISITED_ON,
    AMOUNT,
    ROUND(AMOUNT/7,2) AS AVERAGE_AMOUNT
FROM (
    SELECT 
        DISTINCT VISITED_ON,
        SUM(AMOUNT) OVER(ORDER BY VISITED_ON RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW) AS AMOUNT,
        MIN(VISITED_ON) OVER() AS 1ST_DATE
    FROM CUSTOMER
) AS TABL
WHERE VISITED_ON >= 1ST_DATE+6;