# Write your MySQL query statement below
SELECT 
    S.STUDENT_ID, 
    S.STUDENT_NAME,
    SU.SUBJECT_NAME, 
    COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS S
JOIN SUBJECTS SU 
LEFT JOIN EXAMINATIONS E ON 
        E.STUDENT_ID = S.STUDENT_ID AND
        SU.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY S.STUDENT_ID,SU.SUBJECT_NAME 
ORDER BY S.STUDENT_ID


