# Write your MySQL query statement below
SELECT 
    ACTIVITY_DATE AS DAY,
    COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM ACTIVITY
WHERE ACTIVITY_DATE BETWEEN '2019-06-28' AND '2019-07-27'
GROUP BY ACTIVITY_DATE
