# Write your MySQL query statement below
SELECT 
    ROUND(AVG(B.EVENT_DATE IS NOT NULL),2) AS FRACTION
FROM (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS EVENT_DATE
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) AS A
LEFT JOIN ACTIVITY B ON 
    A.PLAYER_ID = B.PLAYER_ID AND
    DATEDIFF(A.EVENT_DATE, B.EVENT_DATE)=-1
