# Write your MySQL query statement below
SELECT PRODUCT_ID, COALESCE(PRICE, 10) AS PRICE
FROM (
    SELECT DISTINCT PRODUCT_ID
    FROM PRODUCTS
) AS UNIQUEPRODUCTS
LEFT JOIN (
    SELECT DISTINCT PRODUCT_ID, FIRST_VALUE(NEW_PRICE) OVER(
        PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC
    ) AS PRICE
    FROM PRODUCTS
    WHERE CHANGE_DATE <= '2019-08-16'
) AS LASTCHANGEDPRICE USING (PRODUCT_ID);

