# Write your MySQL query statement below
-- SELECT NAME
-- FROM EMPLOYEE
-- WHERE ID IN (
--     SELECT MANAGERID
--     FROM EMPLOYEE
--     WHERE MANAGERID IS NOT NULL
--     GROUP BY MANAGERID
--     HAVING COUNT(*)>=5
-- );

SELECT E1.NAME
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.ID = E2.MANAGERID
GROUP BY E1.ID,E1.NAME
HAVING COUNT(E2.ID)>=5