# Write your MySQL query statement below
SELECT P.PRODUCT_NAME, SUM(O.UNIT) AS UNIT
FROM PRODUCTS P
INNER JOIN ORDERS O USING (PRODUCT_ID)
WHERE O.ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY P.PRODUCT_NAME
HAVING SUM(O.UNIT)>=100
