# Write your MySQL query statement below
SELECT 
    E.EMPLOYEE_ID,
    E.NAME,
    COUNT(E1.EMPLOYEE_ID) AS REPORTS_COUNT,
    ROUND(AVG(E1.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES E
JOIN EMPLOYEES E1 ON E.EMPLOYEE_ID = E1.REPORTS_TO
GROUP BY E.EMPLOYEE_ID
HAVING COUNT(E1.EMPLOYEE_ID)>=1
ORDER BY EMPLOYEE_ID

