# Write your MySQL query statement below
SELECT USER_NAME AS RESULTS
FROM (
    SELECT 
        NAME AS USER_NAME,
        COUNT(*) AS COUNTS
    FROM MOVIERATING R
    JOIN USERS U USING (USER_ID)
    GROUP BY U.USER_ID
    ORDER BY COUNTS DESC, USER_NAME ASC
    LIMIT 1       
) AS GREATRATING

UNION ALL

SELECT TITLE_NAME AS RESULTS
FROM(
    SELECT 
        TITLE AS TITLE_NAME,
        AVG(RATING) AS RATE
    FROM MOVIERATING R
    JOIN MOVIES M USING (MOVIE_ID)
    WHERE SUBSTR(R.CREATED_AT,1,7) = '2020-02'
    GROUP BY R.MOVIE_ID
    ORDER BY RATE DESC, TITLE_NAME ASC
    LIMIT 1
) AS HIGHRATING
