name: Count Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count folders
      id: count_folders
      run: |
        FOLDER_COUNT=$(find . -type d | wc -l)
        echo "Total folders=${FOLDER_COUNT}" >> $GITHUB_ENV
        echo "Updating README with folder count"
        sed -i "s/Total folders: [0-9]*/Total folders: ${FOLDER_COUNT}/" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update folder count"
        git push
